DROP SCHEMA IF EXISTS `bdusuarios` ;
CREATE SCHEMA IF NOT EXISTS `bdusuarios` 

CREATE TABLE IF NOT EXISTS `bdusuarios`.`tarea` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(400) NULL DEFAULT NULL,
  `fechacreacion` VARCHAR(45) NULL DEFAULT NULL,
  `vigente` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
